# Generated by Django 5.2 on 2025-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplayerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
