# Generated by Django 5.2 on 2025-04-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplayerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carrito',
        ),
    ]
