# Generated by Django 5.2 on 2025-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplayerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosregistro',
            name='direccion',
            field=models.CharField(default='pasaje 10', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariosregistro',
            name='contraseña',
            field=models.CharField(max_length=30),
        ),
    ]
