# Generated by Django 5.2 on 2025-05-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplayerapp', '0002_producto_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosregistro',
            name='contraseña',
            field=models.CharField(max_length=256),
        ),
    ]
