# Generated by Django 5.2 on 2025-04-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplayerapp', '0002_remove_cliente_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='oneplayerapp.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('cliente', 'activo')},
        ),
    ]
