# Generated by Django 5.2 on 2025-04-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplayerapp', '0003_alter_carrito_cliente_alter_carrito_unique_together'),
    ]

    operations = [
         # migrations.AlterUniqueTogether(
    #    name='carrito',
    #    unique_together=set(),
    # ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_cliente', to='oneplayerapp.cliente'),
        ),
    ]
